version: '3.4'
services:
  web:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8099:8069"
    entrypoint:
      - odoo
    volumes:
      - <HOST_PATH_FILESTORE>:/var/lib/odoo
      - <PATH_TO_CONFIG>:/etc/odoo
      - <CUSTOM_ADDONS_PATH>:/mnt/extra-addons
    networks:
      - webnet_v2

  db_v:
    image: postgres:12
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - <HOST_PATH_TO_STORE_DB_DATA>:/var/lib/postgresql/data/pgdata
    networks:
      - webnet_v2
volumes:
  <HOST_PATH_FILESTORE>:
  <HOST_PATH_TO_STORE_DB_DATA>:
networks:
  webnet_v2:
  
